### PR TITLE
Fix config check.

### PR DESCRIPTION
**Pull request by vitaliikravets**
Fixed the config check. Added a test.

### CODE REVIEW

**Review by zyrouge — APPROVED** [review]
Oop my bad did it in a hurry, thanks mate!

**Comment by vitaliikravets** [comment]
Hi @zyrouge, can you please publish to NPM?

**Comment by zyrouge** [comment]
> Hi @zyrouge, can you please publish to NPM?

Done :)

**Comment by vitaliikravets** [comment]
Thank you!

**Pull request merged**
